Module4 task1
htmlacademy-react/143091-six-cities-10 pull request #5
Opened 2022-07-25 15:30 UTC by ksenya-7

2022-07-28 18:55 UTC, sahaviev commented on project/public/css/main.css
> +/*! normalize.css v8.0.1 | MIT License | github.com/necolas/normalize.css */html{line-height:1.15;-webkit-text-size-adjust:100%}body{margin:0}main{display:block}h1{font-size:2em;margin:.67em 0}hr{-we
Видимо ты переименовала класс **property__bookmark-icon** через рефакторинг и возможно тут в css файле затронула. Будь осторожнее с этим, в целом минифицированные файлы лучше не трогать

2022-07-28 19:20 UTC, sahaviev commented on project/src/components/card/card.tsx
> +    <article className="cities__card place-card" onMouseEnter={onMouseEnter}>
Ну еще добавить обработчик события на onMouseLeave и в нем ставить setActiveCardId(undefined) чтобы убирать состояние активной карточки при выводе курсора из области карточки.

2022-07-28 22:25 UTC, sahaviev commented on project/src/components/favorite-card/favorite-card.tsx
> +function FavoriteCard(props: OfferFavoriteCardScreenProps): JSX.Element {
Создать отдельный компонент для избранных карточек тоже как вариант, но они почти 1 в 1 совпадают с обычными карточками.
Я бы сделал следующим образом: передавал 2 класса которые должны быть там где это отличается от обычной карты. И передавал бы пустые callback или вообще сделал бы их необязательными для onMouseEnter/onMouseLeave.

2022-07-28 22:26 UTC, sahaviev commented on project/src/components/favorite-card/favorite-card.tsx
> +function FavoriteCard(props: OfferFavoriteCardScreenProps): JSX.Element {
Плюсом такого решения будет то что тебе не нужно будет поддерживать код в нескольких местах. Чуть позже придется добавить опять карточки для NearPlaces.

2022-07-28 22:28 UTC, sahaviev commented on project/src/components/form-review/form-review.tsx
> +        })} */}
Так лучше рендерить звезды эти. Только вынеси массив снаружи и в key передавай просто item, нет необходимости его в строку конвертировать.

2022-07-28 22:29 UTC, sahaviev commented on project/src/components/form-review/form-review.tsx
> +  const fieldChangeHandle = ({target}:ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
handleInputChange

2022-07-28 22:29 UTC, sahaviev commented on project/src/components/list-offers/list-offers.tsx
> +          const keyValue = `${offer.id}`;
так делать не нужно ) Просто подставляй key={offer.id} реакт разбереться

2022-07-28 22:32 UTC, sahaviev commented on project/src/components/list-offers/list-offers.tsx
> +              <Card offer={offer} key={keyValue} onMouseEnter = {() => setActiveCard(offer.id)}/>
Лучше передавай такую функцию:
```
const handleMouseEnter = (offerId) => {
    setActiveCard(offerId);
}
```
А в компоненте Card в onMouseEnter передавай такую функцию(она уже там должна будет определена:
```
const handleMouseEnter = () => {
    onMouseEnter(offer.id);
}
```

Так код будет чище и без анонимных функций

2022-07-28 22:37 UTC, sahaviev commented on project/src/pages/favorites/favorites.tsx
> +                    })}
Тут у тебя на каждом шаге фильтрация по Амстердаму идет, нужно бы это делать где-то в одном месте заранее и потом рендерить

2022-07-28 22:39 UTC, sahaviev commented on project/src/pages/offer/offer.tsx
> +  const offer = offers.filter((item) => item.id === Number(id))[0];
Здесь происходит что-то нехорошее) Нужно просто взять 1 элемент и все =)

2022-07-28 22:40 UTC, sahaviev commented on project/src/pages/offer/offer.tsx
> +  const offer = offers.filter((item) => item.id === Number(id))[0];
Здесь используй `offers.find((item) => item.id === Number(id));`

2022-07-28 22:41 UTC, sahaviev commented on project/src/types/logo.ts
> +};
Пока не увидел нигде у тебя разные размеры лого. 
Мне кажется ты зря сделала это именно так. Это не очень хорошая практика) Расскажу на консультации как это обычно делается.

2022-07-28 22:42 UTC, sahaviev commented on project/src/types/offer.ts
> +export type OfferCard = {
Данный тип можно назвать просто Offer. Никаких других Card в этом проекте у тебя не будет )
Этого названия будет более чем достаточно чтобы понять о каком объекте идет речь

2022-07-28 22:44 UTC, sahaviev commented on project/src/types/offer.ts
> +export type OfferCards = OfferCard[];
Такие типы лучше не создавать. Сейчас это просто создание еще одной сущности которую нужно будет поддерживать.
Там потом в ходе развития проекта что угодно может оказаться.
Читабельность от того что ты будешь использовать Offer[] везде где нужно не пострадает.

2022-07-28 22:44 UTC, sahaviev commented on project/src/types/review.ts
> +};
Я бы не стал вытаскивать это в отдельные типы, это опять же усложнение кода сейчас. Эти данные часть типа Review.

2022-07-28 22:45 UTC, sahaviev commented on project/src/types/review.ts
> +export type OfferCardReview = {
Ну и напоследок этот тип можно лаконично назвать Review. Так будет лучше =)

2022-07-28 22:45 UTC, sahaviev commented on project/src/types/review.ts
> +export type OfferCardReviews = OfferCardReview[];
Данный тип тоже избыточен!

2022-07-28 22:46 UTC, sahaviev commented on project/src/types/offer.ts
> +};
Эти типы часть Offer. Оставь их внутри =)

2022-07-28 22:47 UTC, sahaviev requested changes
Оставил детальное ревью твоего кода.
Я думаю будет лучше если ты все поправишь именно в этом PR, иначе следующий мне будет сложно проверять.
Ничего плохого что я его отправил на доработку нет!

2022-08-03 13:15 UTC, sahaviev-mvptech approved these changes

2022-08-03 13:15 UTC, merged